/**
 * studioHomeDemo.functions.ts
 *
 * Server function that returns 4 pre-composed demo routes for the
 * homepage Studio moment. Each demo is generated by the same engine
 * the Builder uses, so what the homepage shows is what the user
 * actually gets when they enter the Studio — never invented stops,
 * never invented timing.
 *
 * The chips on the homepage map to (intention, regionKey) pairs
 * chosen from the real seeded data. The result is cached in-module
 * for the lifetime of the worker instance.
 */
import { createServerFn } from "@tanstack/react-start";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import {
  type CompatibilityRule,
  type RegionRow,
  type RoutingRules,
  type StopRow,
  generateRoute,
} from "./builderEngine.server";

export type DemoChipKey = "wine" | "coast" | "culture" | "moment";

export interface DemoStopAlternate {
  key: string;
  label: string;
  blurb: string | null;
  tag: string | null;
  variantLabel: string | null;
  durationMinutes: number;
  lat: number;
  lng: number;
}

export interface DemoStop {
  key: string;
  label: string;
  blurb: string | null;
  tag: string | null;
  variantLabel: string | null;
  lat: number;
  lng: number;
  durationMinutes: number;
  driveMinutesFromPrev: number;
  /** Other real variants of the same canonical stop in this region. */
  alternates: DemoStopAlternate[];
}

export interface StudioDemoRoute {
  chip: DemoChipKey;
  intentionLabel: string;
  region: { key: string; label: string; lat: number; lng: number };
  stops: DemoStop[];
  experienceMinutes: number;
  drivingMinutes: number;
  pace: "relaxed" | "balanced" | "full";
  story: string;
}

const CHIP_TO_INPUT: Record<
  DemoChipKey,
  {
    intention:
      | "wine"
      | "coast"
      | "heritage"
      | "wonder";
    intentionLabel: string;
    regionKey: string;
    pace: "relaxed" | "balanced" | "full";
    story: string;
  }
> = {
  wine: {
    intention: "wine",
    intentionLabel: "Wine & food",
    regionKey: "arrabida-setubal",
    pace: "relaxed",
    story:
      "A slow day between Azeitão vineyards and the Sesimbra coast, shaped around wine, lunch and time to enjoy the view.",
  },
  coast: {
    intention: "coast",
    intentionLabel: "Coast & views",
    regionKey: "arrabida-setubal",
    pace: "balanced",
    story:
      "From the bay of Setúbal to the cliffs of Espichel — a quiet stretch of coast that locals keep for themselves.",
  },
  culture: {
    intention: "heritage",
    intentionLabel: "Culture & history",
    regionKey: "sintra-cascais",
    pace: "balanced",
    story:
      "Sintra's palaces, a hidden village on the Atlantic, and a glass of Colares — heritage you can taste.",
  },
  moment: {
    intention: "wonder",
    intentionLabel: "A special moment",
    regionKey: "sintra-cascais",
    pace: "relaxed",
    story:
      "Cabo da Roca at golden hour, a private estate, and a single table waiting for the two of you.",
  },
};

let cached: StudioDemoRoute[] | null = null;
let cachedAt = 0;
const TTL_MS = 5 * 60 * 1000;

async function loadCatalog() {
  const [regionsRes, stopsRes, rulesRes, compatRes] = await Promise.all([
    supabaseAdmin
      .from("builder_regions")
      .select("key,label,blurb,lat,lng")
      .order("sort_order"),
    supabaseAdmin
      .from("builder_stops")
      .select(
        "key,canonical_key,variant_bucket,variant_label,source_tour_keys,region_key,label,blurb,tag,lat,lng,duration_minutes,mood_tags,pace_tags,intention_tags,who_tags,compatible_with,weight",
      )
      .eq("is_active", true),
    supabaseAdmin
      .from("builder_routing_rules")
      .select("*")
      .eq("is_active", true)
      .limit(1)
      .maybeSingle(),
    supabaseAdmin
      .from("builder_compatibility_rules")
      .select("stop_a,stop_b,cooccurrence_count"),
  ]);

  if (regionsRes.error) throw new Error(regionsRes.error.message);
  if (stopsRes.error) throw new Error(stopsRes.error.message);
  if (rulesRes.error) throw new Error(rulesRes.error.message);
  if (compatRes.error) throw new Error(compatRes.error.message);

  const regions = (regionsRes.data ?? []).map((r) => ({
    ...r,
    lat: Number(r.lat),
    lng: Number(r.lng),
  })) as RegionRow[];
  const stops = (stopsRes.data ?? []).map((s) => ({
    ...s,
    lat: Number(s.lat),
    lng: Number(s.lng),
  })) as StopRow[];
  const rules = (rulesRes.data ?? {
    max_experience_hours: 8,
    max_driving_hours: 3,
    min_stops: 3,
    max_stops: 6,
    default_pace: "balanced",
    base_price_per_person_eur: 180,
    pace_multiplier_relaxed: 0.85,
    pace_multiplier_balanced: 1,
    pace_multiplier_full: 1.2,
  }) as RoutingRules;
  const compatibility = (compatRes.data ?? []) as CompatibilityRule[];

  return { regions, stops, rules, compatibility };
}

/**
 * Returns the 4 demo routes used by the homepage Studio moment.
 * Cached server-side so chip taps feel instant.
 */
export const getStudioHomeDemos = createServerFn({ method: "GET" }).handler(
  async (): Promise<{ demos: StudioDemoRoute[] }> => {
    if (cached && Date.now() - cachedAt < TTL_MS) {
      return { demos: cached };
    }

    try {
      const { regions, stops, rules, compatibility } = await loadCatalog();

      const out: StudioDemoRoute[] = [];
      for (const chip of Object.keys(CHIP_TO_INPUT) as DemoChipKey[]) {
        const cfg = CHIP_TO_INPUT[chip];
        const route = generateRoute(
          {
            mood: "slow",
            who: "couple",
            intention: cfg.intention,
            regionKey: cfg.regionKey,
            pace: cfg.pace,
          },
          regions,
          stops,
          rules,
          compatibility,
        );

        // Defensive: only ship demos with ≥3 stops so the line draws meaningfully.
        if (route.stops.length < 3) continue;

        out.push({
          chip,
          intentionLabel: cfg.intentionLabel,
          region: {
            key: route.region.key,
            label: route.region.label,
            lat: route.region.lat,
            lng: route.region.lng,
          },
          stops: route.stops.map((s) => {
            const canonical = s.canonical_key ?? s.key;
            const alternates: DemoStopAlternate[] = stops
              .filter(
                (other) =>
                  other.key !== s.key &&
                  other.region_key === s.region_key &&
                  (other.canonical_key ?? other.key) === canonical,
              )
              .slice(0, 3)
              .map((other) => ({
                key: other.key,
                label: other.label,
                blurb: other.blurb,
                variantLabel: other.variant_label ?? null,
                durationMinutes: other.duration_minutes,
              }));
            return {
              key: s.key,
              label: s.label,
              blurb: s.blurb,
              tag: s.tag,
              variantLabel: s.variant_label ?? null,
              lat: s.lat,
              lng: s.lng,
              durationMinutes: s.duration_minutes,
              driveMinutesFromPrev: s.driveMinutesFromPrev,
              alternates,
            };
          }),
          experienceMinutes: route.totals.experienceMinutes,
          drivingMinutes: route.totals.drivingMinutes,
          pace: route.pace,
          story: cfg.story,
        });
      }

      cached = out;
      cachedAt = Date.now();
      return { demos: out };
    } catch (err) {
      // If the catalog can't be loaded, return an empty list — the UI
      // falls back to a static schematic without breaking the page.
      console.error("getStudioHomeDemos error:", err);
      return { demos: [] };
    }
  },
);
