/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyAuditRouteImport } from './routes/typography-audit'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as MultiDayRouteImport } from './routes/multi-day'
import { Route as LocalStoriesRouteImport } from './routes/local-stories'
import { Route as HeroVerifyRouteImport } from './routes/hero-verify'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DayToursRouteImport } from './routes/day-tours'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BrandQaRouteImport } from './routes/brand-qa'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyHeroRouteImport } from './routes/api/verify-hero'

const TypographyAuditRoute = TypographyAuditRouteImport.update({
  id: '/typography-audit',
  path: '/typography-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiDayRoute = MultiDayRouteImport.update({
  id: '/multi-day',
  path: '/multi-day',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalStoriesRoute = LocalStoriesRouteImport.update({
  id: '/local-stories',
  path: '/local-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroVerifyRoute = HeroVerifyRouteImport.update({
  id: '/hero-verify',
  path: '/hero-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DayToursRoute = DayToursRouteImport.update({
  id: '/day-tours',
  path: '/day-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandQaRoute = BrandQaRouteImport.update({
  id: '/brand-qa',
  path: '/brand-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyHeroRoute = ApiVerifyHeroRouteImport.update({
  id: '/api/verify-hero',
  path: '/api/verify-hero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-qa': typeof BrandQaRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/day-tours': typeof DayToursRoute
  '/experiences': typeof ExperiencesRoute
  '/hero-verify': typeof HeroVerifyRoute
  '/local-stories': typeof LocalStoriesRoute
  '/multi-day': typeof MultiDayRoute
  '/proposals': typeof ProposalsRoute
  '/typography-audit': typeof TypographyAuditRoute
  '/api/verify-hero': typeof ApiVerifyHeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/proposals'
    | '/typography-audit'
    | '/api/verify-hero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/proposals'
    | '/typography-audit'
    | '/api/verify-hero'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand-qa'
    | '/builder'
    | '/contact'
    | '/corporate'
    | '/day-tours'
    | '/experiences'
    | '/hero-verify'
    | '/local-stories'
    | '/multi-day'
    | '/proposals'
    | '/typography-audit'
    | '/api/verify-hero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandQaRoute: typeof BrandQaRoute
  BuilderRoute: typeof BuilderRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  DayToursRoute: typeof DayToursRoute
  ExperiencesRoute: typeof ExperiencesRoute
  HeroVerifyRoute: typeof HeroVerifyRoute
  LocalStoriesRoute: typeof LocalStoriesRoute
  MultiDayRoute: typeof MultiDayRoute
  ProposalsRoute: typeof ProposalsRoute
  TypographyAuditRoute: typeof TypographyAuditRoute
  ApiVerifyHeroRoute: typeof ApiVerifyHeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography-audit': {
      id: '/typography-audit'
      path: '/typography-audit'
      fullPath: '/typography-audit'
      preLoaderRoute: typeof TypographyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-day': {
      id: '/multi-day'
      path: '/multi-day'
      fullPath: '/multi-day'
      preLoaderRoute: typeof MultiDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-stories': {
      id: '/local-stories'
      path: '/local-stories'
      fullPath: '/local-stories'
      preLoaderRoute: typeof LocalStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-verify': {
      id: '/hero-verify'
      path: '/hero-verify'
      fullPath: '/hero-verify'
      preLoaderRoute: typeof HeroVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-tours': {
      id: '/day-tours'
      path: '/day-tours'
      fullPath: '/day-tours'
      preLoaderRoute: typeof DayToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-qa': {
      id: '/brand-qa'
      path: '/brand-qa'
      fullPath: '/brand-qa'
      preLoaderRoute: typeof BrandQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-hero': {
      id: '/api/verify-hero'
      path: '/api/verify-hero'
      fullPath: '/api/verify-hero'
      preLoaderRoute: typeof ApiVerifyHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandQaRoute: BrandQaRoute,
  BuilderRoute: BuilderRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  DayToursRoute: DayToursRoute,
  ExperiencesRoute: ExperiencesRoute,
  HeroVerifyRoute: HeroVerifyRoute,
  LocalStoriesRoute: LocalStoriesRoute,
  MultiDayRoute: MultiDayRoute,
  ProposalsRoute: ProposalsRoute,
  TypographyAuditRoute: TypographyAuditRoute,
  ApiVerifyHeroRoute: ApiVerifyHeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
